steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['clean', 'stage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/dacreed/play-demo', '.']
images: ['gcr.io/dacreed/paly-demo']
tags: ['cloud-builders-community']
